#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Developing Infrastructure to Suppport Periodical Digitization at PUL
#+date: <2024-01-24 Wed>
#+author: Cliff Wulfman
#+email: cwulfman@princeton.edu
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 29.1 (Org mode 9.6.6)
#+cite_export:

* Summary
To be written last.

* Background
- early pilots
- The Daily Princetonian
- The Papers of Princeton
- The Blue Mountain Project

* Current Needs
- newspapers and periodicals already in Figgy are unusable
- curators have newspaper projects they would like to pursue

* Challenges
- newspapers and periodicals do not fit into the current Figgy data
  model
- newspapers and periodicals tend to be large collective objects
- newspapers and periodicals often have different use cases and user
  profiles from other library materials

* Possible Solutions
The following list outlines possible solutions to the challenges.  I
have ranked them from least-desirable to most attractive.

- Do nothing :: One should always consider this option.  There simply
  may not be sufficient motivation to take any action.

- Discontinue digitization of newspapers and periodicals :: The
  newspapers already in Figgy would remain unusable.

- Design and develop an end-to-end solution entirely in-house :: Not
  realistic, given PUL priorities and available resources.

- Modify Figgy and its presentation tools to better handle newspapers
  and periodicals :: Similarly unrealistic, for the same reasons.

- Explore Samvera-based systems :: There was a grant-funded project
  several years ago to develop a Hydra-based system based on the
  Portland Common Data Model.  There are still group calls every few
  months, but https://github.com/samvera-labs/newspaper_works appears
  to be stalled or abandoned.  I don't know of any others.

- Use Veridian :: This seems like the most viable solution.  We
  already license the software; it is world-class and well-supported.

* Analysis
Delivering newspapers and periodicals in Veridian is the most viable
solution to the challenges.

** Drawbacks to Veridian
- it is a commercial product with a non-trivial license fee.

- it requires operations support.

- it uses a different data model from Figgy's.

- adopting it fully would require development of additional workflows
  and staff training.

* Data Model
Veridian relies on two metadata standards to manage and display
digital objects: METS and ALTO.  METS is a standard schema for
encoding descriptive, administrative, and structural metadata about
digital library objects; ALTO is a complementary schema for capturing
content and layout information.  Both standards are maintained by the
Library of Congress; the combination of the two (METS/ALTO) is in
common use in digital libraries around the world.  METS/ALTO is frequently
combined with the MODS schema (also a Library of Congress standard) to
capture bibliographic metadata, but METS is agnostic about descriptive
metadata schemas.

** Why not MARC?
MARC is not well suited for describing periodicals, in particular the
relationships between articles, issues, and titles.  Representation at
the issue level is crucial for digital libraries of newspapers and
periodicals.

** Why not IIIF?
METS/ALTO and the International Image Interoperability Framework
(IIIF) Presentation API are complementary but very different models of
digital objects. IIIF manifests are intended to be lightweight data
structures that can be efficiently transmitted over HTTP and used by
image-viewer applications; METS and ALTO are data representation
schemas that may be used for preservation, discovery, and
display. IIIF manifests can easily be derived from METS/ALTO objects.

* Processing Levels
METS/ALTO creation can be complicated, because the format is very
flexible, but not every METS/ALTO object has to be complex.

** Level 0
A METS object with skeletal descriptive metadata, an inventory of
image files, and a physical structMap outlining page order.

*** Affordances
- minimal discovery
- ordered presentation of page images
*** Effort Estimate
Fully automated production would be feasible.  A simple script to
generate the minimal METS structure from a directory of images.  Code
to generate derivatives (JP2s, Pyramidal TIFFs) could be taken
directly from Figgy (or reconfigured as a common service).

** Level 1
A Level 0 object that also contains one or more detailed descriptive
metadata sections (MARCXML, MODS, BIBFRAME, LRMoo, or other)

*** Affordances
- enhanced discovery
- ordered presentation of page images

** Level 2
A Level 1 object that includes coordinated OCR for each page
(represented in ALTO)

*** Affordances
- enhanced discovery
- full-text search
- ordered presentation of page images
- hit highlighting
- support for annotation

** Level 3
A Level 2 object with constituent-level metadata (in MODS or other
capable metadata schema).

*** Affordances
- constituent-level discovery
- full-text search
- ordered presentation of page images
- hit highlighting
- support for annotation

** Level 4
A Level 3 object with the constituent-level metadata linked to zones
on pages.
*** Affordances
- constituent-level discovery
- full-text search
- ordered presentation of page images
- presentation of regions of interest
- hit highlighting
- support for annotation
  
* Workflows
There are several dimensions to this project, and one is logistical:
the workflows that guide production from title selection through
ingestion.

- METS/ALTO creation is complex but achievable and cost-effective
  - Three-Tiered Approach
    - Outsource Everything
    - Outsource metadata creation
    - Do everything in-house
      - fully automated
      - semi-automated
    
*Scenario:* a curator has a newspaper or periodical title and wants it
"digitized" and made available to patrons.

** Assessment
- Is there a Catalog record?
- Have rights been determined?
- Is the run complete or incomplete?
- Paper originals or microfilm?
- Dimensions?
- Is there in-house language expertise to handle it?
- How large is the run, in terms of volumes, issues, and pages?

** Choice of Processing Option
- Outsource everything. :: Send paper copies or microfilm to an
  established vendor for imaging, and send the digital images to DDD
  for processing into METS/ALTO data.  This is how /The Daily
  Princetonian/ was digitized.  Establishing open-ended contracts with
  vendors and carefully formulated workflows would make it much
  simpler than it has been.

- Outsource metadata creation. :: Scan the pages in-house and send
  them to DDD for processing into METS/ALTO data at NDNP standards
  (see https://www.loc.gov/ndnp/guidelines/).

- Do everything in-house. :: Scan the pages in-house and generate
  bare-bones METS/ALTO metadata through fully automated processes,
  akin to those now used to ingest objects into Figgy from the Digital
  Studio.

Which option to choose depends on several factors including
importance of the material and cost.

** Metadata
Blue Mountain set a very high standard, making extensive use of the
MODS schema to express field values (titles, creators, publishers,
identifiers, etc.) and relationships (constituent-whole
relationships), and the METS Structmap to knit together segments of
text and image produced through zoning and high-accuracy OCR
correction.  The newspapers in the Papers of Princeton collection are
of similar quality, although the constituent-level metadata is
extracted automatically from zoned headlines.

Blue Mountain was a research project, however, and its level of detail
cannot be sustained in ordinary library practice.  Stakeholders should
expect no metadata that cannot be derived from existing catalog
records, which for newspapers and periodicals are notoriously poor,
and which are unlikely to be improved or enhanced for digitization.  A
"first do no harm" approach will be best.

* Scenario 3: Do Everything In-House
The assessment phase remains the same.

** Title Level
*** Descriptive
*** Structural
** Issue Level
*** Descriptive
*** Structural

* From METS/ALTO to Manifest
The IIIF Presentation API is framework derived from the [[https://iiif.io/api/model/shared-canvas/1.0/][Shared Canvas
data model]] which was, in turn, developed to describe digital
facsimiles using a linked-data approach.  The Shared Canvas data model
has been absorbed into the IIIF Presentation API and, it seems,
abandoned for its set of Resources, which are focused on presentation,
not description. The IIIF Manifest is not a substitute for descriptive
or structural metadata.  Rather, it is a /transmission standard/ for
conveying information about digital files (image files, primarily) to
programs that can present those files to a user (on a screen, for
example, in the case of image files).

Generating IIIF Manifests from METS/ALTO data is relatively
straightfoward; see Blue Mountain Springs.
