#+title: Strawberry Project (METS/ALTO generation)
#+date: <2023-06-27 Tue>

* Notes
I've begun to track this project as Strawberry in GitHub Projects;
this discussion will take place separately for now.

There are several dimensions to this project.  One is logistical: the
workflows that guide production from title selection through
ingestion.  We know DDD could do various levels for us, from simple
issue-level to Blue-Mountain-style constituent level with zoning and
OCR correction.  In this first thought train, we're considering how to
do the simplest workflow in-house.

Scenario: a curator has a newpaper or periodical title and wants it
"digitized" and made available to patrons.

- Is there a Catalog record?
- Have rights been determined?
- Is the run complete or incomplete?
- Paper originals or microfilm?
- Is there in-house language expertise to handle it?


** What Standard?
Blue Mountain set a very high standard.  What is the lightest we could
get away with?  Veridian's documentation talks about adhering to the
[[https://www.loc.gov/ndnp/guidelines/][NEH NDNP standards]].  Is PUL able or willing to meet the minimal
standards described in the [[https://www.loc.gov/ndnp/guidelines/NDNP_202224TechNotes.pdf][latest technical guidelines]].

*** Descriptive Metadata
The "no special snowflakes" mandate means expect no metadata that
cannot be derived from an existing catalog record.  Catalog metadata
for newspapers and periodicals is notoriously poor and it will not be
improved or enhanced for digitization.  A "first do no harm" approach
is probably best here.

Princeton's digital applications do not use MODS.  MODS was a standard
for some time, and may still be elsewere; at PUL its use seems to have
been deprecated.  As far as I can tell, for example, Figgy has its own
custom set of metadata fields derived from no standard that I am aware
of and applicable to a limited class of assets.

Blue Mountain makes extensive use of the MODS schema to express field
values (titles, creators, publishers, identifiers, etc.) and
relationships (constituent-whole relationships).

None of this rich metadata is applicable here.  There may not even be
an identifier for the title.

Create a namespace for these things and mint identifiers in it.  This
gives you URIs, and everything else should be linked to those.  Use
conservative schemas: dc, dcterms.


*** Title METS


*** Issue METS
